config/routes.rb
Meddata::Application.routes.draw do
  require 'sidekiq/web'

  resources :articles
  root to: 'articles#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :article_keywords
  has_many :keywords, :through => :article_keywords

  attr_accessible :abstract, :pubmed_id, :raw_pubmed_xml, :title
  


  def extract_pubmed_title(node)
    node.css('PubmedArticle MedlineCitation Article ArticleTitle').first.try(:text)
  end

  def extract_pubmed_abstract(node)
    node.css('PubmedArticle MedlineCitation Article Abstract AbstractText').first.try(:text)
  end

  def extract_pubmed_data!
    extract_pubmed_data.save!
  end
  def extract_pubmed_data_from_node!(node)
    extract_pubmed_data_from_node(node).save!
  end
  def extract_pubmed_data
    doc = Nokogiri.XML(raw_pubmed_xml)
    extract_pubmed_data_from_node(doc)
  end

  def extract_pubmed_data_from_node(node)
    title = extract_pubmed_title(node)
    abstract = extract_pubmed_abstract(node)
  end
  # Extract *all* words and remove some insignificant ones.
  def extract_keywords!
    # TODO: maybe we should collect things based on their p-o-s tags.
    # TODO: add training for tokenizer or use another one which supports
    # learning to enhance specialized word detection.

    t = Treat::Entities::Section.build(Treat::Entities::Title.build(title),Treat::Entities::Paragraph.build(abstract))
    t.apply(:segment, :tokenize, :stem)
    t.each_entity do |ent|
      if ent.has_feature? :stem
        t = ent.stem.downcase
      elsif ent.type == :symbol
        t = ent.to_s.downcase
      else
        next
      end

      # check against stopwords to save some IO

      self.keywords << Keyword.find_or_create_by_title(t)
    end
  end

  def text
    title.to_s+"\n"+abstract.to_s
  end
end

app/models/article_keyword.rb
class ArticleKeyword < ActiveRecord::Base
  belongs_to :article
  belongs_to :keyword
  attr_accessible :kayword_id, :article_id
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  has_many :article_keywords
  has_many :articles, :through => :article_keywords
  attr_accessible :title
  
  def save_keyword_occurrence!(ids=nil)
    articles = ids ? Article.where(id: ids) : Article
    aks=[]
    aid= article_ids
    articles.basic_search(title).each do |article|
      unless aid.include?(article.id)
        aks << article_keywords.new(article_id: article.id)
      end
    end
    ArticleKeyword.import aks
  end

  def neighborhood
    mu_ids = {}
    kwds = ::Keyword.find(articles.all.map{ |i| i.keyword_ids }.flatten.uniq)
    kwds.each do |mu|
      mu_ids[mu.id] = (::Keyword.find(mu).article_ids & article_ids)
    end
    mu_ids
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :html, :json, :js
  def index
    @articles = Article.order('created_at DESC').page(params[:page]).per_page(20)
    respond_with(@articles)
  end

  def show
    @article = Article.find(params[:id])
    respond_with(@article)
  end

  def new
    @article = Article.new
    respond_with(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    @article.save
    respond_with(@article)
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])
    respond_with(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_with(@article)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<% articles.each do |article| %>
  <tr>
    <td><%= link_to article.id, article_path(article) %></td>
    <td><%= article.pubmed_id %></td>
    <td><%= article.title %></td>
    <td><%= article.abstract %></td>
    <td><%= l article.created_at, format: :long %></td>
    <td>
      <%= link_to t("helpers.links.edit_html"), edit_article_path(article),
        :class => 'btn btn-mini' %>
      <%= link_to t("helpers.links.destroy_html"), article_path(article),
        method: :delete, confirm: t("helpers.links.confirm"),
        class: 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>

app/views/articles/_form.html.erb
<%= simple_form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notifications %>
  <div class="form-inputs">
    <%= f.input :pubmed_id %>
    <%= f.input :title %>
    <%= f.input :abstract %>
    <%= f.input :raw_pubmed_xml %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pubmed_id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:abstract) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody id='articles'>
    <%= render 'articles', articles: @articles %>
  </tbody>
</table>
<%= will_paginate %>

app/views/articles/index.js.erb
$('#articles').append('<%= j render( 'articles', articles: @articles ) %>');
<% if @articles.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@articles) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div>
  <div>
    <strong><%= model_class.human_attribute_name(:pubmed_id) %>:</strong>
    <%= @article.pubmed_id %>
  </div>
  <div>
    <strong><%= model_class.human_attribute_name(:title) %>:</strong>
    <%= @article.title %>
  </div>
  <div>
    <strong><%= model_class.human_attribute_name(:abstract) %>:</strong>
    <%= @article.abstract %>
  </div>
  <div>
    <strong><%= model_class.human_attribute_name(:raw_pubmed_xml) %>:</strong>
    <pre><%= @article.raw_pubmed_xml %></pre>
  </div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
    articles_path, :class => 'btn'  %>
  <%= link_to t("helpers.links.edit_html"),
    edit_article_path(@article), :class => 'btn' %>
  <%= link_to t("helpers.links.destroy_html"),
    article_path(@article), :method => 'delete',
    :confirm => t("helpers.links.confirm"),
    :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Meddata" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Meddata</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to Article.model_name.human.pluralize, articles_path %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>